language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - TYPO3=TYPO3_6-2
  - TYPO3=TYPO3_6-1
  - TYPO3=TYPO3_6-0
  - TYPO3=TYPO3_4-7
  - TYPO3=TYPO3_4-6
  - TYPO3=TYPO3_4-5
  
before_script:
  - cd ..
  - mkdir -p typo3conf/ext
  - mv t3x-contexts typo3conf/ext/contexts
  - mkdir t3x-contexts
  - cd t3x-contexts
  - mv ../typo3conf .
  - git clone --single-branch --branch $TYPO3 --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_src
  - ln -sfn typo3_src/typo3 typo3
  - ln -sfn typo3_src/index.php
  - if [[ -d typo3_src/t3lib ]]; then ln -sfn typo3_src/t3lib t3lib; fi
  - echo 'zend.multibyte = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  
script:
  - cd typo3conf/ext/contexts
  - phpunit --coverage-text .

after_script:
  - >
    if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
      echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
      curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
      if [ $? -eq 0 ]; then
        mkdir "$TRAVIS_BUILD_DIR/.build"
        composer init --require=namelesscoder/typo3-repository-client:1.1.x-dev --stability=dev -n -d "$TRAVIS_BUILD_DIR/.build"
        composer install -d "$TRAVIS_BUILD_DIR/.build"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${TRAVIS_TAG} to TER"
        $TRAVIS_BUILD_DIR/.build/vendor/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
      fi;
    fi;
